/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package charming;

import org.junit.jupiter.api.Test;

import charming.actualCode.App;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        //assertNotNull(, "app should have a greeting");
    }
}
